version: "3"
services:

  base:
    container_name: base
    build: ./
    ports:
      - 5000:5000
    depends_on:
      - user
      - product
      - user_products

  user:
    container_name: user
    build: ./user
    ports:
      - 4100:4100
    depends_on:
      - user_db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  product:
    container_name: product
    build: ./product
    ports:
      - 4200:4200
    depends_on:
      - product_db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  user_products:
    container_name: user_products
    build: ./userProducts
    ports:
      - 4300:4300
    depends_on:
      - user_products_db
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=password

  user_db:
    image: mysql
    container_name: user_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      # Expõe a porta modificada do banco
      - 9000:3306

  product_db:
    image: mysql
    container_name: product_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      # Expõe a porta modificada do banco
      - 8000:3306

  user_products_db:
    image: mongo:4.4.14
    container_name: user_products_db
    ports:
      - 7000:27017
networks:
  yout_signature_networks:
