version: "3"
services:

  base:
    container_name: base
    build: "./"
    ports:
      - 4000:4000
    depends_on:
      - user

  user:
    container_name: user
    build: ./user
    ports:
      - 4100:4100
    depends_on:
      - user_db

  product:
    container_name: product
    build: ./product
    ports:
      - 4200:4200
    depends_on:
      - product_db

  user_db:
    image: mysql
    container_name: user_db
    environment:
      MYSQL_ROOT_PASSWORD: password

  product_db:
    image: mysql
    container_name: product_db
    environment:
      MYSQL_ROOT_PASSWORD: password
